<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectScheduleTraining.Application\ProjectScheduleTraining.Application.csproj" />
    <ProjectReference Include="..\ProjectScheduleTraining.CrossCutting\ProjectScheduleTraining.CrossCutting.csproj" />
    <ProjectReference Include="..\ProjectScheduleTraining.Infrastructure\ProjectScheduleTraining.Infrastructure.csproj" />
  </ItemGroup>

</Project>
